apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pokemongo 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pokemongo 
    spec:
      containers:
        -
          name: pokemongo 
          image: gcr.io/nich01as-com/pokemongo:20160723-1
          ports:
            -
              containerPort: 8080
          imagePullPolicy: Always
