apiVersion: v1
kind: Service
metadata:
  name: pokemongo 
  labels:
    run: pokemongo 
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: pokemongo 
  type: LoadBalancer
